### ISSUE TITLE
World analyzer unavailable

### ISSUE THREAD

**Issue by Frutaa** [Razzmatazzz/RemnantSaveGuardian#129] opened 2023-08-20 11:40 UTC
Error log:
Error loading world Data in CharacterData.LoadWorldData: Sequence contains no matching element    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at RemnantSaveGuardian.RemnantWorldEvent.GetInjectables(String saveText) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1566
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1597
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1652
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantCharacter.cs:line 160

**Comment by Razzmatazzz** [comment] 2023-08-20 15:55
Duplicate of #119

**Closed by Razzmatazzz** 2023-08-20 15:55 UTC
