### ISSUE TITLE
Event names don't match what you see in-game

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/RemnantSaveGuardian#9] opened 2023-07-30 11:06 UTC
The event names shown in the analyzer are taken straight from the save files. However, the event names used in the save files don't always match up with what you see in the game. For example, ThreeMenMorris is Postulant's Parlor. The two names don't appear to have anything to do with each other. However, if you Google "three men morris," you quickly see that it refers to the type of game that dungeon is built around. 

The event names can be given translations to match what is in the save files, but that will require some detective work. If you have a save file with an event and you think you the in-game name is something else, please post here. Please include your exported save files in your post and also indicate if there were any other drops in that dungeon (rings, amulets, etc.) to help collect information about how the saves are structured.

**Comment by Frohlemageblanc** [comment] 2023-07-30 14:55
Dran Oracle => Nimue's Retreat

**Comment by demajen** [comment] 2023-07-31 03:44
I did an entire Yaesha adventure mode, scouring everything I could find based on the Adventure tab. The word doc has everything I found, including some speculation about what events are what. I found quite a few more things than were listed in the analyser, which is why I noted everything down in full. Hope it's useful. Your Remnant1 analyzer was awesome!

Hopefully will be able to do another run at some point, but this one took me quite some time. Hopefully I've attached the right stuff as I had to sign up for a github account for this (never used it before!)

[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12211258/save_0.txt)
[Notes for Yaesha Adventure Mode.docx](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12211266/Notes.for.Yaesha.Adventure.Mode.docx)

**Comment by t1nky** [comment] 2023-07-31 15:33
```JSON
{
	"Abyssal Rift": "/Game/World_Nerud/Quests/Quest_Story_IAmLegend/Quest_Story_IAmLegend_Zone1_Template.Quest_Story_IAmLegend_Zone1_Template",
	"Alepsis-Taura": "/Game/World_Nerud/Quests/Quest_Story_TheCore/Quest_Story_TheCore_Nebula_POI.Quest_Story_TheCore_Nebula_POI",
	"Astropath's Respite": "/Game/World_Nerud/Quests/Quest_Miniboss_Phantom/Quest_Miniboss_Phantom_POI.Quest_Miniboss_Phantom_POI",
	"Beatific Gallery": "/Game/World_Fae/Quests/Quest_Boss_FaelinFaerlin/Quest_Boss_FaelinFaerlin_POI.Quest_Boss_FaelinFaerlin_POI",
	"Beatific Palace": "/Game/World_Fae/Quests/Quest_Story_AllFather/Quest_Story_AllFather_Courtyard_POI2.Quest_Story_AllFather_Courtyard_POI2",
	"Blackened Citadel": "/Game/World_Root/Characters/Root_WorldBoss/EventTree/EventTree_RootWorldBoss.EventTree_RootWorldBoss",
	"Briella's Reverie": "/Game/World_Fae/Quests/Quest_OverworldPOI_TheHunter/Quest_Global_TheHunterDream_Template01.Quest_Global_TheHunterDream_Template01",
	"Brocwithe Quarter": "/Game/World_Fae/Quests/Quest_Story_AllFather/Quest_Story_AllFather_DranCity1_Template.Quest_Story_AllFather_DranCity1_Template",
	"Dormant N'Erudian Facility": "/Game/World_Nerud/Quests/Quest_SideD_Extermination/TileTemplates/Template_Extermination_1.Template_Extermination_1",
	"Faithless Thicket": "/Game/World_Jungle/Quests/Quest_Story_Ravager/Quest_Story_Ravager_Overworld_Zone2_Template01.Quest_Story_Ravager_Overworld_Zone2_Template01",
	"Forgotten Field": "/Game/World_Jungle/Quests/Quest_SideD_WailingField/Quest_SideD_WailingField_POI.Quest_SideD_WailingField_POI",
	"Forgotten Prison": "/Game/World_Nerud/Quests/Quest_Story_IAmLegend/Quest_Story_IAmLegend_POI.Quest_Story_IAmLegend_POI",
	"Harvester's Reach": "/Game/World_Fae/Quests/Quest_SideD_CharnelHouse/Quest_SideD_CharnelHouse_Template.Quest_SideD_CharnelHouse_Template",
	"Imperial Gardens": "/Game/World_Jungle/Quests/Quest_SideD_TheTangle/Quest_SideD_TheTangle_POI_2.Quest_SideD_TheTangle_POI_2",
	"Ironborough": "/Game/World_Fae/Quests/Quest_Story_AllFather/Quest_Story_AllFather_DranCity2_Template.Quest_Story_AllFather_DranCity2_Template",
	"Lemark District": "/Game/World_Fae/Quests/Quest_OverworldPOI_ClockTower/Quest_Injectable_ClockKeeper_Template.Quest_Injectable_ClockKeeper_Template",
	"Malefic Gallery": "/Game/World_Fae/Quests/Quest_Boss_FaelinFaerlin/Quest_Boss_FaelinFaerlin_POI.Quest_Boss_FaelinFaerlin_POI",
	"Malefic Palace": "/Game/World_Fae/Quests/Quest_Story_AllFather/Quest_Story_AllFather_Courtyard_POI2.Quest_Story_AllFather_Courtyard_POI2",
	"Phantom Wasteland": "/Game/World_Nerud/Quests/Quest_Story_TheCore/Quest_Story_TheCore_Zone1_Template2.Quest_Story_TheCore_Zone1_Template2",
	"Postulant's Parlor": "/Game/World_Fae/Quests/Quest_SideD_ThreeMenMorris/Quest_ThreeMenMorris.Quest_ThreeMenMorris",
	"Ravager's Lair": "/Game/World_Jungle/Quests/Quest_Boss_Ravager/Quest_Boss_Ravager_POI.Quest_Boss_Ravager_POI",
	"Retreat's Horizon": "/Game/World_Fae/Quests/Quest_Injectable_GoldenHall_Nimue/Quest_Global_NimueDream_POI.Quest_Global_NimueDream_POI",
	"Seeker's Rest": "/Game/World_Nerud/Quests/Quest_Story_TheCore/Quest_Story_TheCore_Start.Quest_Story_TheCore_Start",
	"Sentinel's Keep": "/Game/World_Nerud/Quests/Quest_Boss_NerudGuardian/Quest_Boss_NerudGuardian_POI.Quest_Boss_NerudGuardian_POI",
	"Shattered Gallery": "/Game/World_Fae/Quests/Quest_Miniboss_FaeArchon/Quest_Miniboss_FaeArchon_POI_v4_NoWater.Quest_Miniboss_FaeArchon_POI_v4_NoWater",
	"Spectrum Nexus": "/Game/World_Nerud/Quests/Quest_Miniboss_CustodianEye/Quest_Miniboss_CustodianEye_POI.Quest_Miniboss_CustodianEye_POI",
	"Terminus Station": "/Game/World_Nerud/Quests/Quest_SideD_Train/Quest_SideD_TrainTemplate_POI3.Quest_SideD_TrainTemplate_POI3",
	"The Backrooms": "/Game/World_Labyrinth/Quests/Quest_TheBackrooms/TheBackrooms_Main.TheBackrooms_Main",
	"The Core": "/Game/World_Jungle/Quests/Quest_Story_Empress/Quest_Story_Empress.Quest_Story_Empress",
	"The Eon Vault": "/Game/World_Nerud/Quests/Quest_Story_IAmLegend/Quest_Story_IAmLegend_Zone2_Template.Quest_Story_IAmLegend_Zone2_Template",
	"The Expanding Glade": "/Game/World_Jungle/Quests/Quest_Miniboss_Shrewd/Quest_Miniboss_Shrewd_POI.Quest_Miniboss_Shrewd_POI",
	"The Forbidden Grove": "/Game/World_Jungle/Quests/Quest_Story_Ravager/Quest_Story_Ravager_Overworld_Zone1_Template01.Quest_Story_Ravager_Overworld_Zone1_Template01",
	"The Great Hall": "/Game/World_Fae/Quests/Quest_SideD_Ravenous/Quest_SideD_Ravenous_Template01.Quest_SideD_Ravenous_Template01",
	"The Great Sewers": "/Game/World_Fae/Quests/Quest_Miniboss_BloatKing/Quest_Miniboss_BloatKing_POI_Alt.Quest_Miniboss_BloatKing_POI_Alt",
	"The Labyrinth": "/Game/World_Labyrinth/Quests/Labyrinth_Main.Labyrinth_Main",
	"The Lament": "/Game/World_Jungle/Quests/Quest_SideD_TheLament/Quest_SideD_TheLament_POI.Quest_SideD_TheLament_POI",
	"The Nameless Nest": "/Game/World_Jungle/Quests/Quest_Miniboss_MotherMind/Quest_Miniboss_MotherMind_POI.Quest_Miniboss_MotherMind_POI",
	"The Putrid Domain": "/Game/World_Nerud/Quests/Quest_Miniboss_Abomination/Quest_Miniboss_Abomination_POI_v4.Quest_Miniboss_Abomination_POI_v4",
	"Timeless Horizon": "/Game/World_Nerud/Quests/Quest_Story_TheCore/Quest_Story_TheCore_Zone2_Template1.Quest_Story_TheCore_Zone2_Template1",
	"Vault of the Formless": "/Game/World_Nerud/Quests/Quest_SideD_StasisSiege/Quest_SideD_StasisSiege_Template01.Quest_SideD_StasisSiege_Template01",
	"Void Vessel Facility": "/Game/World_Nerud/Quests/Quest_SideD_TheDreamlessSleep/Quest_SideD_TheDreamlessSleep_POI.Quest_SideD_TheDreamlessSleep_POI",
	"Ward 13": "/Game/World_City/Quests/Quest_Ward13/Ward13_Town.Ward13_Town",
	"Cathedral of Omens": "/Game/World_Jungle/Quests/Quest_SideD_CathedralOfSeasons/Quest_SideD_CathedralOfSeasons_POI.Quest_SideD_CathedralOfSeasons_POI",
	"Cotton's Kiln": "/Game/World_Fae/Quests/Quest_Miniboss_DranGrenadier/Quest_Miniboss_DranGrenadier_POI_v4.Quest_Miniboss_DranGrenadier_POI_v4",
	"Council Chamber": "/Game/World_Fae/Quests/Quest_SideD_FaeCouncil/Quest_SideD_FaeCouncil_Golden_Template.Quest_SideD_FaeCouncil_Golden_Template",
	"Council Tribunal": "/Game/World_Fae/Quests/Quest_SideD_FaeCouncil/Quest_SideD_FaeCouncil_Shaed_Template.Quest_SideD_FaeCouncil_Shaed_Template",
	"Forsaken Quarter": "/Game/World_Fae/Quests/Quest_Story_Asylum/Quest_Story_Asylum_Overworld_DranCity_Zone2_Template1.Quest_Story_Asylum_Overworld_DranCity_Zone2_Template1",
	"Gilded Chambers": "/Game/World_Fae/Quests/Quest_Miniboss_RedPrince/Quest_Miniboss_RedPrince_POI.Quest_Miniboss_RedPrince_POI",
	"Morrow Parish": "/Game/World_Fae/Quests/Quest_Story_Asylum/Quest_Story_Asylum_Overworld_DranCity_Zone1_Template1.Quest_Story_Asylum_Overworld_DranCity_Zone1_Template1",
	"Nimue's Retreat": "/Game/World_Fae/Quests/Quest_Story_Asylum/Quest_Story_Asylum_Nimue_Template.Quest_Story_Asylum_Nimue_Template",
	"Soul Sparks": "/Game/World_Jungle/Quests/Quest_Story_Empress/Quest_Story_Empress.Quest_Story_Empress",
	"The Hatchery": "/Game/World_Nerud/Quests/Quest_Miniboss_Hatchery/Quest_Miniboss_Hatchery_POI_v3.Quest_Miniboss_Hatchery_POI_v3",
	"The Tormented Asylum": "/Game/World_Fae/Quests/Quest_Boss_NightWeaver/Quest_Boss_NightWeaver_Template.Quest_Boss_NightWeaver_Template",
	"Tiller's Rest": "/Game/World_Fae/Quests/Quest_SideD_TownTurnedToDust/Quest_SideD_TownTurnedToDust_POI.Quest_SideD_TownTurnedToDust_POI",
	"Tower of the Unseen": "/Game/World_Nerud/Quests/Quest_SideD_TowerHeist/Quest_SideD_TowerHeist.Quest_SideD_TowerHeist"
}
```
What I've found so far.
I've used this https://gist.github.com/t1nky/19790793842c3c00304626c3106076c2
(save_0.txt) is unpacked save file

**Comment by Razzmatazzz** [comment] 2023-07-31 15:59
I've been working on a new method of parsing events that may provide better information on which events appear where.

**Comment by Razzmatazzz** [comment] 2023-08-01 00:11
It's ugly and will require a lot of cleanup, but can someone with an adventure roll test this and see if the locations look correct?

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223095/RemnantSaveGuardian.zip)

**Comment by demajen** [comment] 2023-08-01 00:18
> It's ugly and will require a lot of cleanup, but can someone with an adventure roll test this and see if the locations look correct?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223095/RemnantSaveGuardian.zip)

Works for me. It does still feature a few lines from other zones, which is odd -- one from Root Eart (Seabed Ship) and 4 from Losomn (Briella's Reverie x2 and Retreat's Horizon x2) . Interestingly nothing random from N'Erud.

HOWEVER, the adventure and Campaign tab contents are now swapped over. I have all the Campaign stuff under Adventure and the Adventure stuff under the Campaign tab.

**Comment by t1nky** [comment] 2023-08-01 00:24
> It's ugly and will require a lot of cleanup, but can someone with an adventure roll test this and see if the locations look correct?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223095/RemnantSaveGuardian.zip)

<img width="526" alt="image" src="https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1833969/6e03a1fb-d57d-4fd3-af4e-86e7438a5e33">

The locations are correct, names are not yet. Tabs are correctly assigned for me for both characters.

**Comment by CrimtS** [comment] 2023-08-01 00:31
Seems to work correctly for me, no extra stuff(only 1 event from root earth). Considering the naming of events we will have to create a map of names, I suppose. It is truly painful work.
Although I have a concern that Butcher's, Cotton and Lemark do not spawn in the same run, but I'm not sure about that.
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/54284301/27dbf629-2290-4885-8c24-8eed7e0015c2)

**Comment by CrimtS** [comment] 2023-08-01 01:06
Also note for the future events names map: 
CrimsonHarvest in butcher's/cotton is the sewers piggy event

**Comment by Razzmatazzz** [comment] 2023-08-01 01:28
I've cleaned up the names further here. @CrimtS can you post the save file with the campaign events that bled over into adventure?

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223520/RemnantSaveGuardian.zip)

**Comment by CrimtS** [comment] 2023-08-01 01:30
Still in the procces of running the world, I need to note that all dungeons are marked correct while open locations(such as Weald, The expanding glade, far woods, etc. are marked as events).
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/54284301/2624b2d5-b060-43e7-b194-533455c58b82)

**Comment by CrimtS** [comment] 2023-08-01 01:30
my current save:
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223538/save_0.txt)
[save_1.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223539/save_1.txt)
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223540/profile.txt)

**Comment by CrimtS** [comment] 2023-08-01 01:33
> Still in the procces of running the world, I need to note that all dungeons are marked correct while open locations(such as Weald, The expanding glade, far woods, etc. are marked as events). ![image](https://user-images.githubusercontent.com/54284301/257381572-2624b2d5-b060-43e7-b194-533455c58b82.png)

To be honest I don't know how to work around seamless location transitions. For example, Koara Kuri nest is a checkpoint inside the Withering weald, but it is marked separately by the save (as you can see, stone of balance drop is linked to the Nest while technically it is inside Withering Weald).

**Comment by CrimtS** [comment] 2023-08-01 01:54
UPD: after running the full world, location naming works correctly. Don't know how to fix this issue 

> while open locations(such as Weald, The expanding glade, far woods, etc. are marked as events).

**Comment by IceVamp** [comment] 2023-08-01 02:47
> I've cleaned up the names further here. @CrimtS can you post the save file with the campaign events that bled over into adventure?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12223520/RemnantSaveGuardian.zip)

Just a thought, but it seems the Dreamcatcher item from Losomn is used for quests in other worlds, might be reason for bleed over?

**Comment by Razzmatazzz** [comment] 2023-08-01 02:50
The most likely reason for the bleed over is the strings I'm using to mark the beginning and ends of the campaign/adventure events aren't ideal.

**Comment by demajen** [comment] 2023-08-01 03:46
Found a really interesting Adventure Mode playthrough of Losomn where Cotton's Kiln, Butcher's Quarter, and Lemark District all exist in the same save.

Lots of issues with this one, unfortunately, from missing items to wrong area names.

The Word doc lists all the items I found, including ones the save analyser didn't show, as well as makes notes about where area names were confused/incorrect. Hope this helps :)

[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12224366/profile.txt)
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12224367/save_0.txt)
[OneTrueKing.docx](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12224373/OneTrueKing.docx)

**Comment by AndrewSav** [comment] 2023-08-01 23:59
Just my two cents.

![2023-08-02_11-41-58](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/46d7a055-ea98-41e0-861d-55ff700bb7cd)
[data.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12234761/data.zip)

**Comment by n2don** [comment] 2023-08-02 22:18
I know why those zones exist, because of the Dream items, they are loaded into every single "base instance" be adventure or campaign, due to the fact you can activate Walker's Dream, Nimue's Dream, Huntress Dream from anywhere.

**Comment by AndrewSav** [comment] 2023-08-03 06:55
> you can activate Walker's Dream, Nimue's Dream, Huntress Dream from anywhere

Sorry, what does this mean? How do you "activate" them?

**Comment by demajen** [comment] 2023-08-03 06:57
> 

They're consumable items you get from using the Dreamcatcher on sleeping individuals (Nimue, the Huntress, or a weird Rooty thing in Root Earth). You can use them in whatever zone you want, and thus I assume the possibility of going to those specific 'dream' locations always has to be loaded into save memory.

**Comment by AndrewSav** [comment] 2023-08-03 06:58
Got it, thank you.

**Comment by AndrewSav** [comment] 2023-08-03 09:32
From TheCustodian PoI, some items from the Drzyr replicator are listed and some are not, these are not listed:

Weapons: Vice Grips /Items/Weapons/Melee/Standard/Claws/Vice_Grips/Weapon_ViceGrips
Amulet: Range Finder /Items/Trinkets/Amulets/RangeFinder/Amulet_RangeFinder
Amulet: Effluvium Enhancer  /Items/Trinkets/Amulets/EffluviumEnhancer/Amulet_EffluviumEnhancer
Ring: Burden of the Mariner /Items/Trinkets/Rings/BurdenOfTheMariner/Ring_BurdenOfTheMariner
Ring: Suppression Ward /Items/Trinkets/Rings/SuppressionWard/Ring_SuppressionWard

**Comment by AndrewSav** [comment] 2023-08-03 09:35
Also it looks like if instead of giving Shining Essence to Custodian you feed it to the replicator you will get Void Idol - have not tried since I do not have Shining Essence yet.

**Comment by AndrewSav** [comment] 2023-08-04 05:59
@Razzmatazzz why are we calling a [mutator](https://remnant2.wiki.fextralife.com/Failsafe) a gem?

![2023-08-04_17-56-37](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/5e981737-4cab-4d43-9a36-9abb9ee0450e)

**Comment by AndrewSav** [comment] 2023-08-04 12:53
Ward 13 mods, always available from mcabe:
- Concussive Shot `/Items/Mods/ConcussiveShot/Mod_ConcussiveShot`
- Scrapshot `/Items/Mods/ScrapShot/Mod_ScrapShot`
- Healing Shot `/Items/Mods/HealingShot/Mod_HealingShot`
- Hotshot `/Items/Mods/HotShot/Mod_Hotshot`

I was not able to find *any* quest items in the character inventory. Unless you know how to identify them things like `Quest: AI Core` will allways be "missing". The code gives `@"/(?<itemType>Quests)/Quest_\w+/Items/(?<itemName>\w+)(?:\.|$)", // quest items` but I do not observe any of these in the profile only in the world save. I dumped all strings in profile.txt before and after obtaining the memory core and there was no substential difference, I think they are a part of the world save. E.g.:

![2023-08-04_21-06-04](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/d6e5fe01-6405-4425-92da-1a19bc6ceaba)


Note, that some story items, such as seeker keys are not listed here, but intermediate "quest" items are. Also note, that when you re-roll adventure any "quest" items disappear. Your campaing quest items are separate. 

I think you can match quest items in the world save on `/Items/Quest` following respectively `/Game/Campaign_Main/Quest_Campaign_Main.Quest_Campaign_Main_C` and `/Quests/Quest_AdventureMode/Quest_AdventureMode`

`game.json` has `/Quests/Quest_SideD_Extermination/Items/Quest_Item_Extermination_AICore` which is [Memory Core II](https://remnant2.wiki.fextralife.com/Memory+Core+II). And there is also `/Quests/Quest_SideD_Train/Items/Quest_Item_Train_AICore` which is [Decorum Cipher](https://remnant2.wiki.fextralife.com/Decorum+Cipher) they both come up as `Quest: AI Core`. If we look them up as suggested above, they won't always display in missing, once aquired, but having them in "missing" feels wrong since are just an "intermediate" items: The lead to [Core Buster](https://remnant2.wiki.fextralife.com/Core+Booster) `/Items/Trinkets/Amulets/CoreBooster/Amulet_CoreBooster` and [Pulse Rifle](https://remnant2.wiki.fextralife.com/Pulse+Rifle) `/Items/Weapons/Longguns/Standard/BurstRifle/Weapon_PulseRifle`. Next to the custodian and drzyr replicator, in the same direct area where Mod_Overflow is we have a gate with two slots: one for Decorum Cipher and the other for Memory Core II. If you have/insert both you get both Core Buster and Pulse Rifle, otherwise only one of the two. May be this can be added to notes.

Another thing I noticed is that I never saw a simulacrum in a save, although they obviously can be found in the world. Any idea why we are not seeing them in saves?

**Comment by Razzmatazzz** [comment] 2023-08-04 13:07
I think we should just ignore quest items for now. I can add a flag so we don't lose the information we currently have on them but they also won't clutter the items list.

**Comment by AndrewSav** [comment] 2023-08-04 19:10
Fair enough

**Comment by AndrewSav** [comment] 2023-08-04 22:39
> I think we should just ignore quest items for now. I can add a flag so we don't lose the information we currently have on them but they also won't clutter the items list.

I think it some situation they needed. For example Override Pin is required to get Aphelion. The program will display Aphelion if Sha'Hala spawns but you cannot get Aphelion unless you have Override Pin, and I do not think that the program will tell you that you can get it at a glance. Something to consider.

**Comment by AndrewSav** [comment] 2023-08-04 23:19
The correct name is [Embrace of Sha'Hala](https://remnant2.wiki.fextralife.com/Embrace+of+Sha'Hala), not "Downgraded Ring" as the program says .

**Comment by AndrewSav** [comment] 2023-08-05 02:56
This name does not seem right:
![023-08-05_14-50-08](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/ba97da4e-8d50-4ee2-9b5b-517e331764f9)

Putrid Domain to me looks like a side dungeon, it has it's own entrance, own crystal inside the entrance, etc. This probably should be call Abyssal Rift instead, this is what displayed in game:
![2023-08-05_14-49-43](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/495c50d1-88b5-4963-8fb8-bb4c6dd58a09)

This is the entrance to Putrid Domain itself, it's quite far away, and it's crystal is inside it not on the overworld map:

![2023-08-05_14-53-10](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/38dfaab7-a163-43a1-bb23-cdaa875f220d)

[data.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12265938/data.zip) - save_1

**Comment by AndrewSav** [comment] 2023-08-05 03:40
"Gravity Anomoly" is misspelt.

**Comment by AndrewSav** [comment] 2023-08-05 05:48
In the save above [Stasis Core](https://remnant2.wiki.fextralife.com/Stasis+Core) that leads to [Statis Bean](https://remnant2.wiki.fextralife.com/Stasis+Beam) is not detected. I can see it in the world and also in save_1: `/Game/World_Nerud/Items/Materials/World/StasisCore/Material_StasisCore.Material_StasisCore_C` My guess that it's a part of IAMLegendStory but I'm not 100% sure.

**Comment by Auricrystal** [comment] 2023-08-05 19:41
Hi, im the one that added the bulk of the event/item list, the reason i included the AICore quest items was because they are used to plug into the basement of the custodian in order to get Core Booster amulet and Pulse Rifle depending on if you have Train dungeon and Dormant N'Erudian Facility, they are less important for tracking directly but mainly just used as a hint to tell the player there is a thing there they want to get because otherwise no info about where you get the AICore's is present in the analyzer and they are both able to be completely overlooked and in some cases entirely locked out of (e.g. Facility).

Up to Razzmatazz to determine a reasonable way to display the conditional information as Pulse rifle is only obtainable with both dungeons present.

**Comment by AndrewSav** [comment] 2023-08-05 22:05
@Auricrystal thank you for your work. If we retain them they should be re-named into their proper names (given above) because AI Core is not what the player sees in the game. I agree that they can be nice as a hint, but the minute you turn them in they will be shown as missing again. We might include some logic that if you already have Core booster/Plasma Rifle, to suppress their display.

**Comment by Razzmatazzz** [comment] 2023-08-07 21:58
We can keep the quest items. I've updated the translation strings for the AI cores.

**Comment by ynot118** [comment] 2023-08-08 07:51
'Dormant N'Erudian Facility' is missing (or possibly incorrectly named) from the analyzer. Latest version 1.0.1.8.

After about 2 hours of re-rolling, 'Dormant' never showed up in the analyzer so I began running through maps to find this zone manually. I can confirm the analyzer does not display this zone.

**Comment by Razzmatazzz** [comment] 2023-08-08 13:03
According to the wiki, Dormant N'Erudian Facility appears to be a location, not an event. Events can sometimes occur in multiple locations. If you're looking for a particular item, it's best to look for that event or item.

That said, some events always appear in particular locations, and we can set the location based on the appearance of that event.

**Comment by ynot118** [comment] 2023-08-08 13:23
Just to clarify, the location 'Dormant N'Erudian Facility' and all it's associated items never came up in the analyzer after hours of re-rolling in adventure mode. In the end I found this location ingame but the analyzer still does not show it.

**Comment by Razzmatazzz** [comment] 2023-08-08 13:25
Understood, and everything I said above still applies. If some events always appear in that location, then we can add the location manually. But that requires knowing which events always show up there.

**Comment by Razzmatazzz** [comment] 2023-08-08 13:34
@ynot118 If you have a save with an "Extermination" event where received or would have received the Siphoner trait, please export via the analyzer and post it here indicating which of your characters (first, second, etc.) had it.

**Comment by ynot118** [comment] 2023-08-08 13:37
No unfortunately I did not keep that save.
 
According to a previous comment from AndrewSav - "@Razzmatazzz why are we calling a mutator gem?", the attached screenshot showed that the analyzer correctly displayed "Dormant Facility".

**Comment by Razzmatazzz** [comment] 2023-08-08 14:12
From what I can tell, the only event that happens in Dormant N'Erudian Facility is Quarantine. Currently, this event is believed to be called "Extermination" in the save files. Until someone can post a save file containing this event and I can confirm what it's called in the actual save, there isn't anything I can do.

**Comment by AndrewSav** [comment] 2023-08-09 06:12
@Razzmatazzz Apologies, but could you please consider this again? Here is what is shown in version 1.0.1.4:
![2023-08-09_18-04-40](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/b5339b7c-57f2-43b2-8fee-e5411c9254a8)

There is Dormant Facility, and there are some items in it shown.

The very same save loaded into 1.0.1.9 shows this:
![2023-08-09_18-07-00](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/1bef20fa-b69a-4808-b4f2-c82f53bc98bd)

Unless I somehow missed it no of the items on the first screenshot are listed here and neither the dungeon.

Second slot, (save_1): 
[data.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12298892/data.zip)

**Comment by Razzmatazzz** [comment] 2023-08-09 21:00
@AndrewSav does this one work better?
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12306897/RemnantSaveGuardian.zip)

**Comment by AndrewSav** [comment] 2023-08-09 23:28
> @AndrewSav does this one work better? [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12306897/RemnantSaveGuardian.zip)

@Razzmatazzz yes, thank you!

**Comment by AndrewSav** [comment] 2023-08-10 05:56
@ynot118 does this work for you?

**Closed** 2023-08-12 11:47 UTC
Labels: enhancement
