### ISSUE TITLE
Archer's Crest spawn conditions are currently uncertain

### ISSUE THREAD

**Issue by LuisBurdallo** [Razzmatazzz/RemnantSaveGuardian#16] opened 2023-08-03 02:31 UTC
Lots of things I already have show as missing items. Ver 1.0.1.0

**Comment by Razzmatazzz** [comment] 2023-08-03 10:35
Please export your save file, post profile.txt here, indicate whether it's your first, second, third, etc. character, and give some examples of items that are erroneously listed as missing.

**Comment by LuisBurdallo** [comment] 2023-08-03 18:39
I have exported the files but I now with the latest version 1.0.11 I can't see the problem again. Let me me check this for a bit to see if the problem persists.

**Comment by Frohlemageblanc** [comment] 2023-08-03 23:42
Well on my end I thought the feature was not there yet (as I always see all items as "missing items" whatever I do)

**Comment by CarlZalph** [comment] 2023-08-04 17:54
- Armor
1. Bruiser set
2. Trainer set
3. Nightstalker set
4. Field Medic set
5. High Noon set
6. Invader set
7. Lodestone Crown
8. Fae Royal set
9. Leto Mark II set
10. Crown of the Red Prince
11. Pilot's Helm
12. Red Widow set
13. Space Worker set
I'm going to stop listing more here, the list in Missing Items for all of the other items in other categories is rather large.  v1.0.1.4
[MissingItems.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12263299/MissingItems.zip)

**Comment by pokeyouman** [comment] 2023-08-04 20:04
Hi,

First, thanks for work.

Your world analyser doesn't show "archers ring" in missing item and probableitems.
I attach my save with endeira's map having the archer ring.
[backup_archers_ring.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12264235/backup_archers_ring.zip)

**Comment by MugmanLord** [comment] 2023-08-04 20:30
Archer's Crest 
https://remnant2.wiki.fextralife.com/Archer's+Crest#gsc.tab=0&gsc.q=endless&gsc.sort=
It is missing in the Missing Items tab. I tried to generate a lot of worlds and it never appeared in the World Analyzer.

**Comment by Razzmatazzz** [comment] 2023-08-06 22:45
@CarlZalph are you listing items that your character has but are shown as missing for that character?

**Comment by Razzmatazzz** [comment] 2023-08-06 22:50
@pokeyouman Are you referring to "Archer's Crest"?
@MugmanLord I see Archer's Crest in Missing Items:
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/35779878/9e1825b0-fa00-4dd9-9f1e-b28f919a94a6)

**Comment by Drannominon** [comment] 2023-08-07 12:27
I also see Archer's Crest in Missing Items list but i think there is something wrong with Archer's Crest in World Analyzer, I rerolled Yesha over 100 times yesterday on all different difficulties and it didnt show up.

**Comment by Razzmatazzz** [comment] 2023-08-07 12:32
It's possible we have the wrong event name associated with Archer's Crest. The only way to find out is for someone with Archer's Crest in their world to post their save.

**Comment by puffbro** [comment] 2023-08-07 13:25
[save_1.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12280232/save_1.zip)
Here's my save with archer's crest in Endaira's End waterfall. It's in adventure mode.

**Comment by Razzmatazzz** [comment] 2023-08-07 14:04
Please use the export save files function of the world analyzer.

**Comment by puffbro** [comment] 2023-08-07 14:08
> Please use the export save files function of the world analyzer.

Here's the exported file.
[save_1.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12280734/save_1.txt)

**Comment by pokeyouman** [comment] 2023-08-07 19:26
@Razzmatazzz Yeah, it's for "Archer's Crest" someone else posted the txt.

**Comment by Razzmatazzz** [comment] 2023-08-07 21:06
@puffbro please also post your profile.txt save file so I can search for it in your inventory.

**Comment by puffbro** [comment] 2023-08-07 21:13
> @puffbro please also post your profile.txt save file so I can search for it in your inventory.

[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12285219/profile.txt)
np here it is.

**Comment by Razzmatazzz** [comment] 2023-08-07 21:47
The ring is indeed named `/Items/Trinkets/Rings/ArchersCrest/Ring_ArchersCrest` in your inventory, so it must drop in conjunction from another event. What other events were present in the area you found it?

**Comment by crackedmind** [comment] 2023-08-07 23:07
Can we add some quest items like keys?  For example, on N'erud in the room behind dzyr replicator you can find the door with 1 or 2 missing keys. I want to know on which location in will drop. Because, i didn't like to remember drop locations.

**Comment by AndrewSav** [comment] 2023-08-07 23:41
Seeker keys from nerud do not appear in the save, if you can find how they are stored when they are in the character's inventory, please let me (and others) know.

**Comment by KittySkin** [comment] 2023-08-08 04:37
[Remnant 2 Saves.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12287272/Remnant.2.Saves.zip)
On my end every single item I own appears as missing in the missing items tab too, for both characters.

**Comment by podizzler3k** [comment] 2023-08-08 09:16
> Well on my end I thought the feature was not there yet (as I always see all items as "missing items" whatever I do). I'll add my files when I have time.

same here the missing items tab just shows everything for me. it would be cool if it just highlighted the missing ones and left the list of everything (its useful to have a list of everything with the wiki shortcuts)

**Comment by puffbro** [comment] 2023-08-08 09:33
> The ring is indeed named `/Items/Trinkets/Rings/ArchersCrest/Ring_ArchersCrest` in your inventory, so it must drop in conjunction from another event. What other events were present in the area you found it?

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/682896b5-f20e-4364-a1c5-dd7b88608187)
The ring spawns in a chest hidden behind an invisible wall with 2 elite enemies in the waterfall room. The waterfall room randomly spawn inside Yaesha Endaira's End dungeon. 

Endaira's End have 3 possible variant, the waterfall room with invisible wall, the library (Atrophy injectable) or a status that plays music.

Guaranteed spawn in Endaira's End would be something like the hidden maze area at the end of the dungeon. With Fester inside as a boss.

A [video ](https://www.youtube.com/watch?v=LWbA0Mf-i6Q)of the archer's crest location

**Comment by Wuxriff** [comment] 2023-08-08 11:18
N'erud - Propulsion Loop and Low Yield Recovery rings are not listed
They both spawn at spectrum nexus for me, both at hidden areas. I can provide save if needed

**Comment by Razzmatazzz** [comment] 2023-08-08 12:27
@puffbro Can you provide an export of your save containing Endaira's End with the ring? If you have multiple characters, please say whether it's your first, second, etc. character.

@Wuxriff Can you provide the export of your save containing those rings on N'Erud?

**Comment by Drannominon** [comment] 2023-08-08 13:09
hidden maze is always there as mentioned before there are 3 versions of endeiras end
- nothing but maze
- library + maze
- wind tower + maze

i had all 3 variations without the ring...

**Comment by Razzmatazzz** [comment] 2023-08-08 13:21
The missing items tab should be fixed in the latest release.

**Comment by puffbro** [comment] 2023-08-08 17:26
> @puffbro Can you provide an export of your save containing Endaira's End with the ring? If you have multiple characters, please say whether it's your first, second, etc. character. I think Archer's Crest just spawns anytime there's the HIddenMaze dungeon, so I can manually add it to that dungeon. I'm still curious if it appears somewhere in the save, though.

[Archer's crest full save.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12294196/Archer.s.crest.full.save.zip)
Here's my full save with Endaira's End with the ring not yet looted on my 2nd character's adventure map (save_1). My character already have the ring in the inventory.

I don't think the ring spawns when there's HiddenMaze dungeon since the HiddenMaze and Fester is a guaranteed spawn. as @Drannominon mentioned. Endaria's End has 3 variants all spawn with the HiddenMaze:

1. Invisible wall with Archer's Crest inside along with 2 elites
2. Library with Burden Of The Follower ring inside along with a mini boss called "Atrophy"
3. Wind tower with Band Band ring inside.

I also have a save with the second library variant and the world analyzer shows the items belongs to the miniboss.
[save_1.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12294238/save_1.txt)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/7498802a-02df-4d07-b243-e3e06cf47df2)

**Comment by Razzmatazzz** [comment] 2023-08-09 00:46
@puffbro if Archer's Crest only spawns when the spawntable is Ziggurat_01, this build should only show it under those circumstances:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12297154/RemnantSaveGuardian.zip)

**Comment by puffbro** [comment] 2023-08-09 03:39
> @puffbro if Archer's Crest only spawns when the spawntable is Ziggurat_01, this build should only show it under those circumstances:
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12297154/RemnantSaveGuardian.zip)

Just ran some tests but seems like `/Game/World_Jungle/TileSets/Ziggurat/Templates/Template_Pan_Ziggurat_03.Template_Pan_Ziggurat_03` isn't the set piece that contains Archer's Crest. 

I'll continue look into which key refers to the waterfall invisible wall set piece.

**Comment by puffbro** [comment] 2023-08-09 04:04
Found `Quest_Injectable_Ziggurat_HiddenChamber`, `Quest_Injectable_Ziggurat_Library/` and `Quest_Injectable_WindHollow`. These could be refering to the 3 variants. Will roll a few world to test.

**Comment by Razzmatazzz** [comment] 2023-08-09 10:46
Can you post an exported save with HiddenChamber?

**Comment by puffbro** [comment] 2023-08-09 11:26
[Endaira's End variants.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12301981/Endaira.s.End.variants.zip)
Here's the export save_1.txt of all 3 variants in adventure mode. Note that for library's save both campaign and adventure have Endaira's in library variant.

**Comment by puffbro** [comment] 2023-08-09 14:54
> This build should only show Archer's Crest in Hidden Maze when the HiddenChamber tileset is present. [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12302841/RemnantSaveGuardian.zip)

Got an error when switching to world analyzer. seems it's not able to parse location after earth.

`Error loading world Data in CharacterData.LoadWorldData: The given key '' was not present in the dictionary.    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, MatchCollection areas, ProcessMode mode) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1152
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1496
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1507
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantCharacter.cs:line 164`

**Comment by Razzmatazzz** [comment] 2023-08-09 20:59
Try this one:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12306887/RemnantSaveGuardian.zip)

**Comment by puffbro** [comment] 2023-08-10 08:34
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/32776ccb-d7ab-4f98-85de-e13b2e878240)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/68324981-f4fa-4e6c-ba92-b6d1f23ae6aa)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/2e7fda6d-339c-4ffb-9d11-806c5d2599f4)

It shows Archer's crest for all 3 variants it seems.

**Comment by Drannominon** [comment] 2023-08-10 09:14
i also did a lot of rerolls with this version and the ring always shows up in the possible items tab but never in the missing items tab (i don't have the ring on my char)

**Comment by Razzmatazzz** [comment] 2023-08-10 12:17
@puffbro @Drannominon does this version work better?
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12312622/RemnantSaveGuardian.zip)

**Comment by Drannominon** [comment] 2023-08-10 13:22
i just rolled 50 Endaira's Ends and got:

16 times only maze
![MZ](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141640594/5d21b8ad-a2db-4369-a39c-55d26d0a4c76)
17 times library
![LB](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141640594/65cc6059-18f7-47e2-864d-f7f59df777f4)
17 times flute tower
![FT](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141640594/e91ef54d-94ef-44b7-8dbd-fa2ea246a094)

all without archer's crest

however when i load puffbro's world from his save i get this result
![AC](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141640594/9a4c01cb-58d9-47bd-b7ce-1f5c9207f59a)

either something still does not work correctly or my game is just bugged and not able to roll a world with the ring

**Comment by Razzmatazzz** [comment] 2023-08-10 13:24
It's possible the method I'm using from looking at puffbro's save isn't reliable.

**Comment by puffbro** [comment] 2023-08-10 15:03
@Drannominon I would guess those rolls without either library or flute tower is the hidden chamber (archer's crest) variant. Would it be possible to see if that's the case?

My save file with archer's crest is before the patch so I'm not sure if that affects anything.

**Comment by razeedazee** [comment] 2023-08-11 00:56
First of all, hi and thanks for this great app. Started using it recently. Now for the business end.

This is how you should be able to tell from the current results and the image below is from my confirmed area save backups i taxi people with.

![2023-08-11_01-34-29](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/f75f7cfe-bf86-45a5-95d2-848cd5eea602)

- Version 1 - Burden of the follower + Hidden library 

  No Flute tower injectable and Atrophy injectable. Atrophy is always in the hidden library which means you have burden of the follower which means you can't have the other variations

- Version 2 - Waterfall - Archers crest

  No Flute injectable and no Atrophy injectable. This should be the waterfall. it does not show the archers crest item in RSG for me but it's there, see my proof below.

- Version 3 - Wind puzzle

  Flute tower injectable - cannot be other variations.

Here is a screen shoo RSG loaded with me at Archers Crest.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/95550be9-8e88-42e9-a4b6-52e1302999b0)

Ding me with same user name in Remnant discord to get my saves if you need them,

**Comment by razeedazee** [comment] 2023-08-11 01:15
Just to add, i believe the area for Archers crest is an injectable (if i understand them correctly)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/695231f4-fbc0-4f58-b56b-69536059301c)

Like the Atrophy injectable area i think maybe includes the burden ( or the other way around?)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/080cfe0c-d203-4f4d-9dfe-ebc59f502124)

Here it is

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/e3b2dfff-1131-484b-98bc-f299794c3636)

**Comment by AndrewSav** [comment] 2023-08-11 09:08
> Ding me with same user name in Remnant discord to get my saves if you need them,

I'm not a dev, your help is appreciated, but you might consider, that people do not have time to chase people on discord or elsewhere. **This** is the right place to post the saves and it helps the dev(s) greatly to correlate the facts if the saves are presents *and* match your screenshots too (as opposed to your saves several days from now, if someone did hypothetically got around to pinging you ;).

**Comment by razeedazee** [comment] 2023-08-11 10:04
Honestly, it's neither an on topic or a particularly helpful reply. 

If i had seen the [comments about exporting](https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/16#issuecomment-1663745359) when i skimmed the thread i would have known there was a built in method to export the data to attach to the comments, which is the only correct reply. Also i was referring to my large collection of saves for a majority of items and instances which i use in the [#remnant2-pc-get](https://discord.com/channels/439222927876030464/1139057775494844518) channel.

Suggestion: The export feature is more obvious or documented on the readme or both as i was looking for it in wrong place until i realised it's just that little icon in the world analyser, right?

When i look at the exported profile attached for `Version 2 - Waterfall - Archers crest`  i see this:

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/d35a196c-c444-40b6-b05d-94a73904c4e5)

[EXPORTS.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12320379/EXPORTS.zip)

**Comment by razeedazee** [comment] 2023-08-11 10:48
Here is another Yaesha roll with another `Version 2 - Waterfall - Archers crest` which i assumed correctly would be a waterall variant for lack of Flute injectable and Atrophy injectable

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/6b123fff-ea01-435c-b809-80f924381391)

[EXPORTS.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12320658/EXPORTS.zip)

The layout of this area is different.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/6a3828c9-7ab2-4c72-ab9d-307b4bbe2966)

**Comment by Drannominon** [comment] 2023-08-11 11:06
i just checked one without library and wind tower and the waterfall is really there, i guess i was just really unlucky when i checked multiple endeiras ends before the app launched.
i will test a few more later just to be sure that every version without library or wind tower has the ring

**Comment by Drannominon** [comment] 2023-08-11 11:51
yeah 2 times in a row endeira's end without tower or library and it had the waterfall
they even had different layouts so i think its safe to say that the version without library and tower always has waterfall/archer's crest
i can test a bit more tomorrow if you want but i think its solved

**Comment by razeedazee** [comment] 2023-08-11 12:08
I do think the area is an injectable though. There is a basic layouts with 3 injectable tilesets?

Library
Waterfall
Wind Tower

But i guess maybe the waterfall is not the injectable name? There are always two elites in the area. Not sure of their names. They always spawn in a pair. These two are guaranteed to spawn in that area.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/45af5fd8-abc6-4be8-a2f1-a3521da889e7)

**Comment by Razzmatazzz** [comment] 2023-08-11 12:58
I think I finally got it:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12321677/RemnantSaveGuardian.zip)

**Comment by razeedazee** [comment] 2023-08-11 13:15
Instance 1 - no change

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/860f7f9b-852a-42a6-9de2-542f5042d631)

[EXPORTS.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12321795/EXPORTS.zip)

In the area i last attached, old vs new

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/3318ea7d-298d-4b05-9d0f-413de5d821b5)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/5e7d2d4e-981c-44c7-8f41-4691abd84d94)

**Comment by Razzmatazzz** [comment] 2023-08-11 13:16
Is this correct, or should it also show up in the first instance?

**Comment by razeedazee** [comment] 2023-08-11 13:19
These are both unique waterfall instances

**Comment by Razzmatazzz** [comment] 2023-08-11 13:22
Does the HiddenChamber event show up in the saves where you have found Archer's Crest?

**Comment by razeedazee** [comment] 2023-08-11 13:25
Both those examples have waterfall + archers crest but only one shows injectable hidden chamber with the build you linked.

I guess it means that it's not that?

**Comment by puffbro** [comment] 2023-08-11 13:31
> Both those examples have waterfall + archers crest but only one shows injectable hidden chamber with the build you linked.
> 
> I guess it means that it's not that?

Can you upload the specific world save that have waterfall + archers crest but does not show injectable hidden chamber in RSG? both in .sav and .txt format.

**Comment by razeedazee** [comment] 2023-08-11 14:03
I can do but first, am i using the linked build or the release, since it's also showing me this on a Wind puzzle instance

Release top / [Linked build bottom](https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/16#issuecomment-1674748700)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/f8bf4cb4-74f5-4320-95f8-4f6e981a1f38)

**Comment by Razzmatazzz** [comment] 2023-08-11 14:29
The test build should display all the events of the release build plus some additional injectables.

**Comment by Razzmatazzz** [comment] 2023-08-11 14:50
Possibly; it tries to insert the missing injectables as best it can but it's not perfect.

**Comment by razeedazee** [comment] 2023-08-11 14:58
Both exported with latest release. I think compact is the best one to test. It is be best variation of the waterfall variant i found so far, for being the most compact map. It's possible the second, larger example has an undiscovered, secret area that the compact version does not. They both have the waterfall though.

I've explored the entire map and left collectables unopened.

When using the linked build i see this 

Compact

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/4e487944-53c4-4597-8975-b783d958be2e)

Large

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/141931230/341e477f-c0c7-4750-80a7-28078f2f780c)



[endairas-end-archers-crest-compact.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12322651/endairas-end-archers-crest-compact.zip)
[endairas-end-waterfall-archers-crest-large.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12322652/endairas-end-waterfall-archers-crest-large.zip)

**Comment by JohnnyxxS2** [comment] 2023-08-11 18:59
Archer's Crest spawned in my adventure, but it shows that it spawned in Cathedral of Omens instead of Endaira's End. Confirmed Archer's Crest is in fact in Endaira's End.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/7387766/8c6e43a8-2525-4767-9a21-1c04fb66b6f6)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/7387766/00f615fb-179e-4ed9-8372-666dc739ae0d)

**Comment by Razzmatazzz** [comment] 2023-08-11 20:18
Can you post the save (original is fine, no export needed)? The process of adding in the injectables doesn't always provide a reliable way of putting them in the right spot, but collecting more information could help.

**Comment by JohnnyxxS2** [comment] 2023-08-11 21:04
@Razzmatazzz not sure if that save file has the Archer's Crest already picked up or not. I think I picked it up and then did a backup on the SaveGuardian, but I'm not sure if the game actually saves until I die or touch a worldstone.

**Comment by eswiig** [comment] 2023-08-12 08:46
have this been fixed in 1.0.1.12 or still working on it? I've been rerolling for 2 days and still nothing

**Comment by eswiig** [comment] 2023-08-12 08:54
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/58608430/d19a72e3-a551-4c25-b257-556bda0b215d)
first time it showed up in World Analyzer, although in wrong location. I will explore Endaria's end and see if I can find it.

**Comment by Drannominon** [comment] 2023-08-12 08:59
if you don't have the Injectable "Flute Tower" or "Atrophy" it should be the layout with archer's crest

as the dev has mentioned before the injectable for the hidden chamber/archer's crest shows up in wrong locations atm but should still be in endeira's end

**Comment by eswiig** [comment] 2023-08-12 09:53
can confirm, 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/58608430/27968967-5f8d-4711-a4b6-5a63c4bed0af)

and this is the waterfall people are talking about (first time I ever saw it, the door is through the wall I pinged (gotta space bar through it))
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/58608430/f0e740ec-6706-4197-9b09-8fbd084627d0)

**Comment by Razzmatazzz** [comment] 2023-08-14 14:45
So aside from possibly displaying in the wrong location, does the analyzer correctly show an event when the ring is present?

**Comment by eswiig** [comment] 2023-08-16 05:53
I don't have enough data on that as I only tried once, but It seems it's correct. Maybe others can attest.

**Comment by Razzmatazzz** [comment] 2023-08-17 20:45
Closing this issue as I believe the problem has been fixed.

**Closed by Razzmatazzz** 2023-08-17 20:45 UTC
Labels: bug, question
