### ISSUE TITLE
"latest version is 1.4.0.0, you are on 1.4.0" with most recent release (sunday sept 29)

### ISSUE THREAD

**Issue by kadamwolfe** [Razzmatazzz/RemnantSaveGuardian#282] opened 2024-09-29 13:04 UTC
I just downloaded and upacked the [latest release](https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/tag/1.4.0.0) 1.4.0.0 and on opening it complains i am on 1.4.0, `update` from app fails.

![image](https://github.com/user-attachments/assets/0aaf9453-dcfb-46cf-ad91-a6b3f83987bc)

**Comment by Razzmatazzz** [comment] 2024-09-29 18:04
Duplicate of #281

**Closed by Razzmatazzz** 2024-09-29 18:04 UTC
