### ISSUE TITLE
vault of the formeless 

### ISSUE THREAD

**Issue by NoobbyTV** [Razzmatazzz/RemnantSaveGuardian#60] opened 2023-08-09 12:44 UTC
its call underground stasis instead 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/6b7f8c70-b374-47e9-9e18-958923d9c191)

**Comment by NoobbyTV** [comment] 2023-08-09 12:52
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/d923595a-c54c-4276-8271-fa830ebfadbd)

**Comment by Razzmatazzz** [comment] 2023-08-09 21:12
Will be fixed in the next version, and duplicate of #45.

**Closed by Razzmatazzz** 2023-08-09 21:12 UTC
