### ISSUE TITLE
Location Name Version 1.0.1.9

### ISSUE THREAD

**Issue by dcao3** [Razzmatazzz/RemnantSaveGuardian#54] opened 2023-08-08 23:49 UTC
Just wanted to report that location names for just N'Erud are showing up as something different in this version.

See screencap below. Underground_Stasis is supposed to be Putrid Domain (mine spawned with flooded room).

But then you also see another dungeon called Underground Stasis and that's another dungeon entirely. 

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/12177637/f4306eb2-539d-42c5-840e-e7db5fc99ed5)

**Comment by Razzmatazzz** [comment] 2023-08-09 00:13
What item(s) did you get from the StasisSiege event?

**Comment by dcao3** [comment] 2023-08-09 01:57
For StasisSiege, I got Metal Driver and Rupture Cannon. It was the Vault of the Formless.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/12177637/7ade0121-cc6a-4ae4-98a9-a18236070fa9)

**Comment by Razzmatazzz** [comment] 2023-08-09 21:08
Other than the overworld name, these should all be fixed in the next version.

**Comment by Razzmatazzz** [comment] 2023-08-09 21:09
Closing this as a duplicate of #45.

**Closed by Razzmatazzz** 2023-08-09 21:09 UTC
