### ISSUE TITLE
Wrong locations and boss in campaign

### ISSUE THREAD

**Issue by LuisBurdallo** [Razzmatazzz/RemnantSaveGuardian#17] opened 2023-08-03 02:48 UTC
I have explored Losomn inside out and it tells me there are places that are not in that roll. Also, it says the boss was Faeron ( which is Faerin) And Faelin but the world boss was the Nightweaver. The whole thing was around the Sanatorium and not the Palace. The second boss was Magister Dullain and not Fealin. Ver 1.0.1.0

**Comment by Razzmatazzz** [comment] 2023-08-03 13:03
I've fixed the Faeron/Faerin typo for the next release, but the rest of this is a duplicate of #12 .

**Closed by Razzmatazzz** 2023-08-03 13:03 UTC
Labels: duplicate

**Comment by LuisBurdallo** [comment] 2023-08-03 13:26
I see thanks I didn't realize it was already mentioned.
