### ISSUE TITLE
Adventure and Campaign tabs transposed

### ISSUE THREAD

**Issue by davidcwilkerson** [Razzmatazzz/RemnantSaveGuardian#29] opened 2023-08-04 20:32 UTC
Version 1.0.1.4
It looks like the adventure and campaign tabs are still switched.  It still works pretty well so thanks for the hard work :)  Also, I was wondering if the Navigation room/plasma cutter shows up or not because I had it in my world and I didn't see it in the analyzer.  I keep rerolling but it never shows up in the analyzer so I thought maybe it is a hidden item or something. Thanks

**Comment by Wuxriff** [comment] 2023-08-05 12:44
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/2a2419db-016b-4614-bb19-9137568dc94f)
This is a POI and it does not have a fixed location, a wrecked ship can be in several places

**Comment by Razzmatazzz** [comment] 2023-08-06 22:42
Duplicate of #15

**Closed by Razzmatazzz** 2023-08-06 22:42 UTC
