### ISSUE TITLE
World Analyzer (Error)

### ISSUE THREAD

**Issue by Muraysi** [Razzmatazzz/RemnantSaveGuardian#191] opened 2023-11-18 17:01 UTC
![2023-11-18_11h39_35](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/31324029/94bf7f13-7792-407a-abd6-043d817bc711)

I am currently experiencing issues while trying to use my character information. After importing the information, I keep receiving an error message which causes the application to buffer continuously. As a result, I am unable to add, modify, or remove any data. The application remains stuck in a loading loop and if I attempt to backup, it automatically closes. Whenever I reopen it, the same issue recurs. Therefore, I am reaching out to you for assistance. I hope there is a solution to fix this problem.

**Comment by Razzmatazzz** [comment] 2023-11-22 14:25
Closing as duplicate of #192

**Closed by Razzmatazzz** 2023-11-22 14:25 UTC
Labels: duplicate
