### ISSUE TITLE
Adventure tab doesn't update after i rerolled a new adventure

### ISSUE THREAD

**Issue by cemsapa** [Razzmatazzz/RemnantSaveGuardian#68] opened 2023-08-10 18:22 UTC
So i rolled some new adventures and its stuck in Yaesha

**Comment by sinnoaria** [comment] 2023-08-10 20:07
To trigger a save, you can also double swap modes to campaign, then back to adventure.

**Comment by sds1993** [comment] 2023-08-10 23:55
I have exactly the same issue. Tried travel and double swap but the issue still happened. 
The adventure progress is stuck in Yaesha

**Comment by sds1993** [comment] 2023-08-10 23:59
> Did you travel to the world? Just re-rolling doesn't trigger a save, but traveling does.

I am sorry to bother you kind sir, but I actually have exactly the same issue with him. 
I did try travel worlds or double swap between campaign and adventure but the issue still there. The adventure progress was stuck in progress no matter what I did.

**Comment by sds1993** [comment] 2023-08-11 10:39
> Does this build work better for you?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12317925/RemnantSaveGuardian.zip)

Thank you for your reply! Sadly, no. the issue is still there.
However, I found that the Adventure progress of my first (primary) character would be updated in my second character, it is weird and may be where the bug comes from.
Meaning that I have my first character with Campaign A and Adventure A. For the progress of Adventure A, rather than supposed to be updated in the first save slot of the Save Guardian, it is updated in the second save slot, which is my second character. And the progress of it in the first slot is stuck in Yaesha like forever.

**Comment by sds1993** [comment] 2023-08-11 10:49
> Does this build work better for you?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12317925/RemnantSaveGuardian.zip)

Problem solved.
I checked the saves folder of my game and deleted all (.bak) and (-copy) extension files and your Save Guardian worked like a charm!

**Comment by Razzmatazzz** [comment] 2023-08-11 10:50
Did you happen to delete a character at some point? That can cause problems with matching characters to worlds. If you select the other character for now, it should show the world info you need.

**Comment by sds1993** [comment] 2023-08-11 10:59
> Did you happen to delete a character at some point? That can cause problems with matching characters to worlds. If you select the other character for now, it should show the world info you need.

Yes, that might be the reason.

**Comment by Razzmatazzz** [comment] 2023-08-11 16:42
Closing this as the original issue has probably been fixed in the latest release. If anyone else experiences the world analzyer showing events for the wrong character, please create a new issue.

**Closed by Razzmatazzz** 2023-08-11 16:42 UTC
