### ISSUE TITLE
Adventure Mode / Campaign are swapped

### ISSUE THREAD

**Issue by Frohlemageblanc** [Razzmatazzz/RemnantSaveGuardian#15] opened 2023-08-01 15:33 UTC
Title. With previous and current release, both tabs are actually swapped.

**Comment by Frohlemageblanc** [comment] 2023-08-01 16:02
For unknown reasons, the issue did disappear when I rerolled an adventure (but did stay on all rerolls for story). Will see what's going on.

**Comment by AndrewSav** [comment] 2023-08-01 23:55
@Razzmatazzz  So I worked on alternative method independently, and the same problems are reported and seen in the latest build as I had with my method, so we probably arrived at similar ones. This in particular I 've seen to, you can reproduce this by re-rolling a campaign on a character. It should be possible to detect which is which because adventure ostensibly have less zones than campaign. I have not looked at your latest code yet, so this is just a conjecture.

**Comment by MattSr92** [comment] 2023-08-02 01:12
On v1.0.0.5 and I see this as well. My buddy using RSG says that his is fine, so maybe some kind of situational condition causing this?

[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12235018/profile.txt)
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12235019/save_0.txt)

**Comment by Frohlemageblanc** [comment] 2023-08-02 08:39
Your buddy can reproduce it by rerolling a campaign (and tp into it). If you run an adventure mode, thoses two are not swapped.

**Comment by Razzmatazzz** [comment] 2023-08-03 01:16
This may be fixed in the latest release.

**Comment by Razzmatazzz** [comment] 2023-08-03 14:54
@MattSr92 @Frohlemageblanc let me know if this issue is persisting with the latest release.

**Comment by Frohlemageblanc** [comment] 2023-08-03 23:41
Seems to work right now. So I guess you can close it for the time being.

**Comment by MattSr92** [comment] 2023-08-04 02:44
I just had it happen again on v1.0.1.3

[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12256543/profile.txt)
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12256544/save_0.txt)

**Comment by Razzmatazzz** [comment] 2023-08-07 21:55
This should hopefully be fixed now for good with the latest release.

**Closed** 2023-08-08 14:17 UTC
Labels: bug, question
